HTML Report v16

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -34,19 +34,25 @@ jobs:
       - name: Run Playwright tests
         run: npx playwright test --reporter=dot,html
 
+      - name: List Coverage Directory
+        run: |
+          echo "Listing contents of the working directory:"
+          ls -R .
+          echo "Checking for coverage report:"
+          ls -R ./coverage-report || echo "Coverage report not found"
+
       - name: Setup Pages
-        if: github.ref == 'refs/heads/main'
+        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         uses: actions/configure-pages@v3
 
       - name: Upload Artifact
-        if: github.ref == 'refs/heads/main'
+        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         uses: actions/upload-pages-artifact@v1
         with:
-          # location of the coverage artifacts
           path: "./coverage-report"
 
   deploy-coverage:
-    if: github.ref == 'refs/heads/main'
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     runs-on: ubuntu-latest
     needs: test
     
@@ -55,7 +61,6 @@ jobs:
       id-token: write
 
     environment:
-      # environment created automatically by GitHub
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
 
